node('maven') {
    stage('Checkout') {
        checkout scm
        sh "ls -l"
    }
    stage('Create projects') {
        def projects = readJSON file: "pipelines/clustermonkey/projects/project-spec-poc.json"
        for (project in projects) {
            echo "${project.name} - ${project.description}"
        }
    }
}