node('maven') {
    stage('Checkout') {
        checkout scm
        sh "ls -l"
    }
    stage('Create projects') {
        def projects = readJSON file: "pipelines/clustermonkey/projects/project-spec-poc.json"
        for (project in projects) {
            sh "oc adm new-project ${project.name} --display-name='${project.displayname}' --description='${project.description}' --admin=${project.admin}"
        }
    }
}